#name: Create binary for release
#
## Only on tags that start with a "v"
#on:
#  push:
#    tags:
#      - "v*"
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - target: x86_64-pc-windows-gnu
#            archive: zip
#          - target: x86_64-unknown-linux-musl
#            archive: tar.gz tar.xz
#          - target: x86_64-apple-darwin
#            archive: zip
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Compile and release
#        uses: rust-build/rust-build.action@v1.3.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          RUSTTARGET: ${{ matrix.target }}
#          ARCHIVE_TYPES: ${{ matrix.archive }}
